# Generated by Django 2.2.12 on 2021-03-07 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApp', '0003_auto_20210307_0258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lists',
        ),
        migrations.AlterField(
            model_name='task',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 2, 59, 30, 923086, tzinfo=utc)),
        ),
    ]
