# Generated by Django 2.2.12 on 2021-03-07 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApp', '0005_auto_20210307_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 6, 56, 16, 512325, tzinfo=utc)),
        ),
    ]
