# Generated by Django 2.2.12 on 2021-03-07 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApp', '0006_auto_20210307_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 7, 2, 32, 883983, tzinfo=utc)),
        ),
    ]
