# Generated by Django 2.2.12 on 2021-03-07 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApp', '0008_auto_20210307_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 8, 6, 46, 609787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 8, 6, 46, 625104, tzinfo=utc)),
        ),
    ]
