# Generated by Django 2.2.12 on 2021-03-07 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApp', '0010_auto_20210307_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='list_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trelloApp.Lists'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lists',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 10, 9, 48, 975219, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 10, 9, 48, 991035, tzinfo=utc)),
        ),
    ]
