# Generated by Django 2.2.12 on 2021-03-09 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trelloApp', '0011_auto_20210307_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 11, 31, 51, 657687, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 11, 31, 51, 672401, tzinfo=utc)),
        ),
    ]
