# Generated by Django 2.2.12 on 2021-03-11 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='note',
            field=models.TextField(default='start'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 7, 8, 42, 526539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 7, 8, 42, 526150, tzinfo=utc)),
        ),
    ]
