# Generated by Django 2.2.12 on 2021-03-15 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workingApp', '0003_auto_20210314_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_list',
            name='user',
        ),
        migrations.AlterField(
            model_name='list_board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 15, 6, 39, 30, 988799, tzinfo=utc)),
        ),
    ]
